server.port=8083
spring.application.name=order-service

spring.data.cassandra.contact-points=${SHOPPING_CASSANDRA_CONTACT_POINTS:127.0.0.1}
spring.data.cassandra.port=${SHOPPING_CASSANDRA_PORT:9042}
spring.data.cassandra.keyspace-name=${SHOPPING_CASSANDRA_KEYSPACE:online_shopping_order}
spring.data.cassandra.local-datacenter=${SHOPPING_CASSANDRA_DATACENTER:datacenter1}
spring.data.cassandra.schema-action=create_if_not_exists
spring.data.cassandra.request.timeout=10s
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SHOPPING_AUTH_JWK_SET_URI:http://localhost:8081/oauth2/jwks}
spring.kafka.bootstrap-servers=${SHOPPING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=true

shopping.services.item.base-url=${SHOPPING_ITEM_SERVICE_BASE_URL:http://localhost:8082}
shopping.services.account.base-url=${SHOPPING_ACCOUNT_SERVICE_BASE_URL:http://localhost:8081}
shopping.kafka.topic.order-placed=${SHOPPING_KAFKA_ORDER_PLACED_TOPIC:shopping.order.placed.v1}

management.endpoints.web.exposure.include=*
