server.port=8082
spring.application.name=item-service

spring.data.mongodb.uri=${SHOPPING_MONGO_URI:mongodb://localhost:27017/online_shopping_item}
spring.data.mongodb.auto-index-creation=true
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SHOPPING_AUTH_JWK_SET_URI:http://localhost:8081/oauth2/jwks}

management.endpoints.web.exposure.include=*
