server.port=8080
spring.application.name=gateway-service

spring.cloud.gateway.routes[0].id=account-static
spring.cloud.gateway.routes[0].uri=${SHOPPING_ACCOUNT_SERVICE_BASE_URL:http://localhost:8081}
spring.cloud.gateway.routes[0].predicates[0]=Path=/,/*.html,/storefront.css,/storefront.js,/favicon.ico

spring.cloud.gateway.routes[1].id=auth-service
spring.cloud.gateway.routes[1].uri=${SHOPPING_ACCOUNT_SERVICE_BASE_URL:http://localhost:8081}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/auth/**,/oauth2/**,/.well-known/**,/api/v1/oauth2/**

spring.cloud.gateway.routes[2].id=account-service
spring.cloud.gateway.routes[2].uri=${SHOPPING_ACCOUNT_SERVICE_BASE_URL:http://localhost:8081}
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/shopping/accounts/**

spring.cloud.gateway.routes[3].id=item-service
spring.cloud.gateway.routes[3].uri=${SHOPPING_ITEM_SERVICE_BASE_URL:http://localhost:8082}
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/shopping/items/**

spring.cloud.gateway.routes[4].id=order-service
spring.cloud.gateway.routes[4].uri=${SHOPPING_ORDER_SERVICE_BASE_URL:http://localhost:8083}
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/shopping/orders/**,/api/v1/shopping/carts/**

spring.cloud.gateway.routes[5].id=payment-service
spring.cloud.gateway.routes[5].uri=${SHOPPING_PAYMENT_SERVICE_BASE_URL:http://localhost:8084}
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/shopping/payments/**

management.endpoints.web.exposure.include=*
